"""Initial migration

Revision ID: 1eb85fa55153
Revises:
Create Date: 2025-03-17 09:40:01.704616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from app.utils.extentions import gen_uuid, hash_password
from app.core.config import settings, Roles, AccountStatuses

# revision identifiers, used by Alembic.
revision: str = "1eb85fa55153"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("role", sa.String(), server_default="User", nullable=True),
        sa.Column("dob", sa.DateTime(), nullable=True),
        sa.Column(
            "create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "update_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            onupdate=sa.func.now(),
        ),
        sa.Column("status", sa.String(), server_default="Active", nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_table(
        "user_refresh_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="Active", nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_refresh_tokens_id"), "user_refresh_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_refresh_tokens_refresh_token"),
        "user_refresh_tokens",
        ["refresh_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_refresh_tokens_user_id"),
        "user_refresh_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    admin_user = {
        "id": gen_uuid(),
        "name": settings.ADMIN_NAME,
        "email": settings.ADMIN_EMAIL,
        "phone": settings.ADMIN_PHONE,
        "password": hash_password(settings.ADMIN_PASSWORD),
        "role": Roles.ADMIN.value,
    }

    users_table = sa.table(
        "users",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("email", sa.String),
        sa.column("phone", sa.String),
        sa.column("password", sa.String),
        sa.column("role", sa.Integer),
    )

    op.bulk_insert(users_table, [admin_user])


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    session = Session(bind=bind)

    try:
        session.execute(
            sa.text("DELETE FROM users WHERE email = :email"),
            {"email": settings.ADMIN_EMAIL},
        )
        session.commit()
    finally:
        session.close()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_refresh_tokens_user_id"), table_name="user_refresh_tokens"
    )
    op.drop_index(
        op.f("ix_user_refresh_tokens_refresh_token"), table_name="user_refresh_tokens"
    )
    op.drop_index(op.f("ix_user_refresh_tokens_id"), table_name="user_refresh_tokens")
    op.drop_table("user_refresh_tokens")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
