"""Initial migration

Revision ID: 2cd1dea06efc
Revises:
Create Date: 2025-03-14 11:26:50.693625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from app.utils.extentions import gen_uuid, hash_password
from app.core.config import settings, Roles

# revision identifiers, used by Alembic.
revision: str = "2cd1dea06efc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("role", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###

    admin_user = {
        "id": gen_uuid(),
        "name": settings.ADMIN_NAME,
        "email": settings.ADMIN_EMAIL,
        "password": hash_password(settings.ADMIN_PASSWORD),
        "role": Roles.ADMIN.value,
    }

    users_table = sa.table(
        "users",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("email", sa.String),
        sa.column("password", sa.String),
        sa.column("role", sa.Integer),
    )

    op.bulk_insert(users_table, [admin_user])


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    session = Session(bind=bind)

    try:
        session.execute(
            sa.text("DELETE FROM users WHERE email = :email"),
            {"email": settings.ADMIN_EMAIL},
        )
        session.commit()
    finally:
        session.close()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
